version: '2'
services:
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:9.4"
    environment:
      POSTGRES_PASSWORD: hunter2
      POSTGRES_USER: postgres
  web:
    build: .
    ports:
      - "80:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis